version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"

  app:
    image: node:18       # Use a Node image directly
    command: node        # Or any other safe command
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
